<a href="https://colab.research.google.com/github/riyalguha/TensorFlow_basics/blob/main/TensorFlow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [3 5 1]
 [1 5 6]
 [2 3 8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    [[10,2,0],
     [1,0,2]],
    [[5,8,0]
     ,[2,7,0]],
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [ ]:
tensor_three_d.ndim

3

In [ ]:
tensor_four_d=tf.constant([
 [
    [[1,2,0],
     [3,5,-1]],
    [[10,2,0],
     [1,0,2]],
    [[5,8,0]
     ,[2,7,0]],
    [[2,1,9],
     [4,-3,32]]
],
[
    [[13,26,0],
     [13,15,-10]],
    [[1,21,10],
     [11,20,22]],
    [[15,18,10]
     ,[2,7,0]],
    [[22,21,29],
     [24,-32,32]]
],
[
    [[11,12,10],
     [31,15,-11]],
    [[110,21,10],
     [11,10,21]],
    [[15,81,10]
     ,[21,71,10]],
    [[21,11,91],
     [41,-13,32]]
]
 ])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[ 13  26   0]
   [ 13  15 -10]]

  [[  1  21  10]
   [ 11  20  22]]

  [[ 15  18  10]
   [  2   7   0]]

  [[ 22  21  29]
   [ 24 -32  32]]]


 [[[ 11  12  10]
   [ 31  15 -11]]

  [[110  21  10]
   [ 11  10  21]]

  [[ 15  81  10]
   [ 21  71  10]]

  [[ 21  11  91]
   [ 41 -13  32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
# changing the datatype of a tensor from integer to float
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.float32)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["Hello World","Hi","Hey"])
print(tensor_string)

tf.Tensor([b'Hello World' b'Hi' b'Hey'], shape=(3,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
np_array=np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor_from_nparray = tf.convert_to_tensor(np_array)
print(converted_tensor_from_nparray)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
tensor_eye = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(tensor_eye)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [1,3,4],5,name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
ones_tensor= tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
ones_like_tensor= tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
#shape of tensor 't' is [2,2,3]
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.rank(t)
# tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.62629  98.75391]
 [101.04674 100.06829]
 [ 99.96516  98.41479]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype = tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([ 4  3 46 70  0], shape=(5,), dtype=int32)


In [ ]:
tensor_indexing=tf.constant([3,6,2,4,6,66,7])
print(tensor_indexing[:])
print(tensor_indexing[0:4])
print(tensor_indexing[0::2])
print(tensor_indexing[0:-1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([3 2 6 7], shape=(4,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d[:3,:2])
print(tensor_two_d[:3,:])
print(tensor_two_d[2,:])
print(tensor_two_d[:,0])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 0]
 [3 5 1]
 [1 5 6]], shape=(3, 3), dtype=int32)
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    [[10,2,0],
     [1,0,2]],
    [[5,8,0]
     ,[2,7,0]],
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d[0,:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
x_argmax=tf.constant([
                      [2,20,30,3,6],
                      [3,11,16,1,8],
                      [14,45,23,5,27]
                      ])
print(tf.math.argmax(x_argmax,1))
print(tf.math.argmin(x_argmax,1))

tf.Tensor([2 2 1], shape=(3,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,1],
    [1,5,6],
    [2,3,8]
],dtype=tf.float16)
print(tf.math.reduce_sum(tensor_two_d,axis=1,keepdims=True,name=None))
print(tf.math.reduce_max(tensor_two_d,axis=1,keepdims=True,name=None))
print(tf.math.reduce_min(tensor_two_d,axis=1,keepdims=True,name=None))
print(tf.math.reduce_mean(tensor_two_d,axis=0,keepdims=True,name=None))
print(tf.math.reduce_std(tensor_two_d,axis=0,keepdims=True,name=None))

tf.Tensor(
[[ 3.]
 [ 9.]
 [12.]
 [13.]], shape=(4, 1), dtype=float16)
tf.Tensor(
[[2.]
 [5.]
 [6.]
 [8.]], shape=(4, 1), dtype=float16)
tf.Tensor(
[[0.]
 [1.]
 [1.]
 [2.]], shape=(4, 1), dtype=float16)
tf.Tensor([[1.75 3.75 3.75]], shape=(1, 3), dtype=float16)
tf.Tensor([[0.829 1.299 3.346]], shape=(1, 3), dtype=float16)


In [ ]:
print(tf.math.top_k(tensor_two_d))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)


In [ ]:
x_1=tf.constant([[1,2,0],
                 [3,5,-1]])
x_2=tf.constant([[1,2,0],
                 [3,5,-1]
                 ])
tf.linalg.matmul(
    x_1,x_2,transpose_a=True,transpose_b=False,adjoint_a=False,adjoint_b=False,
    a_is_sparse=False,b_is_sparse=False,output_type=None,name=None
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 17, -3],
       [17, 29, -5],
       [-3, -5,  1]], dtype=int32)>

In [ ]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [ ]:
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,100],
                          [1,5,6],
                          [2,3,8]])
print(tf.linalg.band_part(tensor_two_d,0,0))#Gives Diagonal
print(tf.linalg.band_part(tensor_two_d,0,-1))#Gives Upper Triangular Matrix
print(tf.linalg.band_part(tensor_two_d,-1,0))#Gives Lower Triangular Matrix

tf.Tensor(
[[1 0 0]
 [0 5 0]
 [0 0 6]
 [0 0 0]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[  1   2   0]
 [  0   5 100]
 [  0   0   6]
 [  0   0   0]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [3 5 0]
 [1 5 6]
 [2 3 8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_two_d=tf.constant([[1,2,0,10],
                          [3,5,100,12],
                          [1,5,6,2],
                          [2,3,8,0]],dtype=tf.float32)
tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [ ]:
print(tensor_two_d_inv)

tf.Tensor(
[[ 1.2412921e-01 -2.9765673e-02 -4.4205201e-01  7.0360994e-01]
 [-4.8131734e-02 -8.8663707e-03  2.9385689e-01 -1.0956303e-01]
 [-1.2982901e-02  1.0766308e-02  3.1665713e-04 -9.8163402e-03]
 [ 9.7213425e-02  4.7498420e-03 -1.4566176e-02 -4.8448391e-02]], shape=(4, 4), dtype=float32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    [[10,2,0],
     [1,0,2]],
    [[5,8,0]
     ,[2,7,0]],
    [[2,1,9],
     [4,-3,32]]
])
x_expanded = tf.expand_dims(tensor_three_d,axis=0)
print(x_expanded)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(1, 4, 2, 3), dtype=int32)


In [ ]:
x_squeezed = tf.squeeze(x_expanded,axis=0)
print(x_squeezed)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tf.reshape(x_expanded,[4,2,3]))

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [8]:
t1=[[1,2,3],
    [4,5,6]]
t2=[[7,8,9],
    [10,11,12]]
print(tf.concat([t1,t2],axis = 0))
print(tf.concat([t1,t2],axis = 1))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [9]:
 print(tf.stack([t1,t2],axis=1).shape)

(2, 2, 3)


In [10]:
t=tf.constant([[1,2,3],[4,5,6]])
padding = tf.constant([1,1],
                      [2,2])
tf.pad(t,padding,"CONSTANT")

TypeError: ignored

In [11]:
indices = [[2],
           [1]]
params = [['a','b'],
          ['c','d'],
          ['e','f']]
tf.gather_nd(params,indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'e', b'f'],
       [b'c', b'd']], dtype=object)>

In [18]:
indices = [[0,1],[1,0]]
params = [[['a0','b0'],
           ['c0','d0']],
          [['a1','b1'],
           ['c1','d1']]]
indices_1 = [[0,1,0],[1,0,1]]
tf.gather_nd(params,indices)
tf.gather_nd(params,indices,batch_dims=1)#batch_dims makes it aware of the batch pre-selects dimensions

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b0', b'c1'], dtype=object)>

In [16]:
tf.gather_nd(params,indices_1)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'c0', b'b1'], dtype=object)>

In [19]:
indices = [[[0,1],
            [1,0]],
           [[0,0],
            [1,1]]]
tf.gather_nd(params,indices,batch_dims=1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b0', b'c0'],
       [b'a1', b'd1']], dtype=object)>

## Ragged Tensors

In [20]:
tensor_two_d=[[1,2,0],
              [3],
              [1,5,6,5,7],
              [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)

(4, None)


### Lets us store tensors which are not rectangular

In [21]:
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 7], [2, 3]]>


In [29]:
print(tf.RaggedTensor.from_row_lengths(
    values = [3,1,4,1,5,9,2,6],
    row_lengths = [4,0,3,1,0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [27]:
print(tf.RaggedTensor.from_row_limits(
    values = [3,1,4,1,5,9,2,6],
    row_limits = [4,4,7,8,8]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [28]:
print(tf.RaggedTensor.from_row_splits(
    values = [3,1,4,1,5,9,2,6],
    row_splits = [0,4,4,7,8,8]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


## Sparse Tensors

In [30]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]], values=[11,56],dense_shape=[5,6]
)

In [31]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [32]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

## String Tensors

In [33]:
tensor_string = tf.constant(["Hello","i am","a string"])
print(tensor_string)

tf.Tensor([b'Hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [35]:
tf.strings.join(tensor_string,separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello i am a string'>

## Variables

In [37]:
x=tf.constant([1,2])
x_var= tf.Variable(x,name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [38]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [39]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 6], dtype=int32)>

In [2]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)
print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0
